### ISSUE TITLE
Trojan/Trojan-go

### ISSUE THREAD

**Issue by poopsterbate** [kizimirua/NEWIFI-D2-OpenWrt#11]
Hello,
![image](https://user-images.githubusercontent.com/63714625/106383733-8809fc00-6402-11eb-85d9-e08211fda237.png)

There is no support for Trojan/Trojan-go. If it is possible to do so, can you please add these in the next release?

Thanks

**Comment by kizimirua** [comment]
![0](https://user-images.githubusercontent.com/38457218/106383809-dc14e080-6402-11eb-858f-3d6e3b4a8012.png)
