### ISSUE TITLE
请问如何保存设置？

### ISSUE THREAD

**Issue by SeawolfMao** [kizimirua/NEWIFI-D2-OpenWrt#7]
每次重启或者断电就会恢复默认设置了……

**Comment by SeawolfMao** [comment]
我在breed内刷了openwrt-ramips-mt7621-d-team_newifi-d2-initramfs-kernel.bin，重启，断电后配置都会重置为初始。然后在openwrt luci内更新openwrt-ramips-mt7621-d-team_newifi-d2-squashfs-sysupgrade.bin，然后就可以保存配置了……不知道是什么原因。

**Comment by kizimirua** [comment]
breed更新固件也用squashfs-sysupgrade.bin
