### ISSUE TITLE
作者你好

### ISSUE THREAD

**Issue by andylughua** [kizimirua/NEWIFI-D2-OpenWrt#9]
2款固件可以考虑加入usb打印共享吗 ？感谢

**Comment by kizimirua** [comment]
https://github.com/kizimirua/NEWIFI-D2-OpenWrt/releases/tag/2020.11

**Comment by andylughua** [comment]
谢谢付出

**Comment by hoangminh88** [comment]
> https://github.com/kizimirua/NEWIFI-D2-OpenWrt/releases/tag/2020.11

What this version? 18.03/19.07/Snapshot?

**Comment by kizimirua** [comment]
Compile based on this [repository：[https://github.com/coolsnowwolf/lede](url)
